security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto
            # Autres paramètres de hashage...

    providers:
        app_user_provider:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_login
                
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine
                
            # Supprimer la configuration form_login car elle entre en conflit avec custom_authenticator
            
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/verify, roles: PUBLIC_ACCESS }
        - { path: ^/resend-otp, roles: PUBLIC_ACCESS }
        # Autres règles d'accès...