controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_home:
    path: /
    controller: App\Controller\HomeController::index

# Registration and Authentication Routes
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: [GET, POST]

app_verify_otp:
    path: /verify
    controller: App\Controller\VerificationController::verify
    methods: [GET, POST]

app_resend_otp:
    path: /resend-otp
    controller: App\Controller\VerificationController::resendOtp
    methods: [GET]

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

# Product Routes (Frontend)
app_product_index:
    path: /products
    controller: App\Controller\ProductController::index
    methods: [GET]

app_product_show:
    path: /products/{id}
    controller: App\Controller\ProductController::show
    methods: [GET]

# Admin Routes
app_admin_dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

# Admin Category Routes
app_admin_category_index:
    path: /admin/category
    controller: App\Controller\Admin\CategoryController::index
    methods: [GET]

app_admin_category_new:
    path: /admin/category/new
    controller: App\Controller\Admin\CategoryController::new
    methods: [GET, POST]

app_admin_category_show:
    path: /admin/category/{id}
    controller: App\Controller\Admin\CategoryController::show
    methods: [GET]

app_admin_category_edit:
    path: /admin/category/{id}/edit
    controller: App\Controller\Admin\CategoryController::edit
    methods: [GET, POST]

app_admin_category_delete:
    path: /admin/category/{id}
    controller: App\Controller\Admin\CategoryController::delete
    methods: [POST]

# Admin Product Routes
app_admin_product_index:
    path: /admin/product
    controller: App\Controller\Admin\ProductController::index
    methods: [GET]

app_admin_product_new:
    path: /admin/product/new
    controller: App\Controller\Admin\ProductController::new
    methods: [GET, POST]

app_admin_product_edit:
    path: /admin/product/{id}/edit
    controller: App\Controller\Admin\ProductController::edit
    methods: [GET, POST]

app_admin_product_show:
    path: /admin/product/{id}
    controller: App\Controller\Admin\ProductController::show
    methods: [GET]

app_admin_product_delete:
    path: /admin/product/{id}
    controller: App\Controller\Admin\ProductController::delete
    methods: [POST]

# Checkout Routes
app_checkout:
    path: /checkout
    controller: App\Controller\CheckoutController::index
    methods: [GET, POST]

app_order_stripe_success:
    path: /order/stripe/success
    controller: App\Controller\CheckoutController::stripeSuccess
    methods: [GET]

app_order_stripe_cancel:
    path: /order/stripe/cancel
    controller: App\Controller\CheckoutController::stripeCancel
    methods: [GET]

# CORRECTED: Point the confirmation route to the OrderController
app_order_confirmation:
    path: /order/confirmation/{reference}
    controller: App\Controller\OrderController::confirmation # <-- Corrected controller
    methods: [GET]


# ADDED: Route for downloading the invoice PDF
app_order_download_invoice:
    path: /order/{reference}/invoice
    controller: App\Controller\OrderController::downloadInvoice
    methods: [GET]

# Admin Order Routes
app_admin_order_index:
    path: /admin/order
    controller: App\Controller\Admin\OrderController::index
    methods: [GET]

app_admin_order_show:
    path: /admin/order/{id}
    controller: App\Controller\Admin\OrderController::show
    methods: [GET, POST]

app_admin_order_update_status:
    path: /admin/order/{id}/update-status
    controller: App\Controller\Admin\OrderController::updateStatus
    methods: [POST]

app_admin_order_resend_confirmation:
    path: /admin/order/{id}/resend-confirmation
    controller: App\Controller\Admin\OrderController::resendConfirmation
    methods: [POST]
