controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_verify_otp:
    path: /verify
    controller: App\Controller\VerificationController::verify
    methods: [GET, POST]

app_resend_otp:
    path: /resend-otp
    controller: App\Controller\VerificationController::resendOtp
    methods: [GET] 